# Generated by Django 5.2.4 on 2025-10-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TideDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weekday', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Tide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('time', models.TimeField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tides', to='mare_backend.tideday')),
            ],
            options={
                'ordering': ['day__date', 'order'],
                'unique_together': {('day', 'order')},
            },
        ),
    ]
